//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeOtomasyonu.WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adisyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adisyon()
        {
            this.Siparis = new HashSet<Siparis>();
            this.Siparis1 = new HashSet<Siparis>();
        }
    
        public int adisyonID { get; set; }
        public int masaID { get; set; }
        public int kullaniciID { get; set; }
        public System.DateTime tarih { get; set; }
        public decimal ucret { get; set; }
        public Nullable<int> odemetipID { get; set; }
        public bool acikMi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Masa Masa { get; set; }
        public virtual Masa Masa1 { get; set; }
        public virtual OdemeTip OdemeTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis1 { get; set; }
    }
}
