//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeOtomasyonu.WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int menuID { get; set; }
        public string menuAdi { get; set; }
        public string menuIcerik { get; set; }
        public decimal menuFiyati { get; set; }
    }
}
