//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeOtomasyonu.WF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeVTContext : DbContext
    {
        public cafeVTContext()
            : base("name=cafeVTContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adisyon> Adisyon { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<MasaTip> MasaTip { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<MiktarTur> MiktarTur { get; set; }
        public virtual DbSet<OdemeTip> OdemeTip { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<stok> stok { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
    }
}
