//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeOtomasyonu.WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int siparisID { get; set; }
        public int adisyonID { get; set; }
        public int urunID { get; set; }
        public int miktar { get; set; }
        public int miktarTurID { get; set; }
    
        public virtual Adisyon Adisyon { get; set; }
        public virtual Adisyon Adisyon1 { get; set; }
        public virtual MiktarTur MiktarTur { get; set; }
        public virtual MiktarTur MiktarTur1 { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual Urun Urun1 { get; set; }
    }
}
